# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161002183156 on 2016-10-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161030_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product/no_img.jpg', upload_to='images/product/'),
        ),
    ]
